SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP DATABASE IF EXISTS `PRIMER_AI_DATA`;

CREATE SCHEMA IF NOT EXISTS `PRIMER_AI_DATA` DEFAULT CHARACTER SET latin1;
USE `PRIMER_AI_DATA` ;

CREATE TABLE IF NOT EXISTS `PRIMER_AI_DATA`.`CITY_DATA` (
  `genome_id` INT(20) NOT NULL,
  `nearest_genome_id` INT(20) DEFAULT NULL,
  `geo_bucket_id` VARCHAR(100) DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `longitude` INT(20) NULL DEFAULT NULL,
  `latitude` INT(20) NULL DEFAULT NULL,
  `country_code` VARCHAR(2) NOT NULL,
  `administrative_level_1` VARCHAR(20) NOT NULL,
  `administrative_level_2` VARCHAR(80) NOT NULL,
  `SHAPE_DATA` BLOB NOT NULL,
  PRIMARY KEY (`genome_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10007
DEFAULT CHARACTER SET latin1;

CREATE TABLE IF NOT EXISTS `PRIMER_AI_DATA`.`KD_TREE` (
  `geo_bucket_id` VARCHAR(100) NOT NULL,
  `longitude` INT(20) DEFAULT NULL,
  `lattitude` INT(20) DEFAULT NULL,
  `square_count` VARCHAR(100) NOT NULL,
  `element_count` INT(20) NOT NULL,
  PRIMARY KEY (`geo_bucket_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10007
DEFAULT CHARACTER SET latin1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

